source :gemcutter
source "http://gems.github.com"
source "http://rubygems.org"
gem "rails", "2.3.5"
gem "sqlite3-ruby", :require => "sqlite3"
gem "laserlemon-vestal_versions", :require => "vestal_versions"
gem "authlogic"
gem "be9-acl9", :require => "acl9"
gem "formtastic"
gem "simple-navigation"
gem "acts-as-taggable-on"
gem "sunspot", :require => "sunspot"
gem "sunspot_rails", :require => "sunspot/rails"
